language: python
python:
  - "3.5"

services:
  - postgresql

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/olist

before_script:
  - psql -c 'create database olist;' -U postgres
  - cp test.env .env
  - cd work-at-olist

install:
  - pip install -r requirements-test.txt

script: 
  - coverage run --source=channels,workatolist ./manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)
