# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
